[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "Unescaping the `String` easily"
edition     = "2021"
homepage    = "https://unescaper.hack.ink"
license     = "GPL-3.0"
name        = "unescaper"
readme      = "README.md"
repository  = "https://github.com/hack-ink/unescaper"
version     = "0.1.0"

[dependencies]
thiserror = { version = "1.0" }
